export const START_FETCHING = "START_FETCHING";

export const FETCHING_DATA = "FETCHING_DATA";
export const FETCHING_SUCCESSFULL = "FETCHING_SUCCESSFULL";
export const FETCHING_ERROR = "FETCHING_ERROR";
